Project-Enumerables-Custom implementation of ruby enumerable methods
Zubenna/project-enumerables pull request #1
Opened 2020-05-24 14:50 UTC by Zubenna

# Summary of code

2020-05-25 05:05 UTC, lekegitrepo commented
#### Hi @Zubenna :clap: :clap:
#### Well done, you did a good job so far. However, you need to improve the following methods :point_down: before this project can be approved.

- my_all?
- my_any?
- my_none?
- my_inject

_**They did not output the expected result**_

**_fix these and submit for review_**

### _Reviewed by Temitayo Adeleke._

2020-05-25 05:06 UTC, lekegitrepo requested changes
#### Status: Request changes

2020-05-25 17:01 UTC, Zubenna commented
I have modified the methods pointed out.

2020-05-25 19:16 UTC, shshamim63 requested changes
## Status :recycle: Required Changes :rocket: 
___
Hi @Zubenna :wave: , almost there. Just need to resolve couple of corner cases and then you will be done with it. Let's get to those cases.
___
### :spades: Mandatory Changes :spades: 
___
- Check out the inline comments below to resolve them.
___
### :clubs: Optional Changes :clubs: 
___
- You should not make any change to the given rubocop configuration. But you have done it. Please check out this [link](https://github.com/microverseinc/linters-config/tree/master/ruby). This is a crucial requirement. But as the previous reviewer forgot it to mention I am adding it in the optional tag.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-05-25 19:16 UTC, shshamim63 commented on custom_enumerable_methods.rb
> +  end
`my_each` identical and returns the same thing as ruby's [`each`](https://ruby-doc.org/core-2.6.4/Array.html#method-i-each). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_each.png) from [Odin](https://github.com/TheOdinProject/curriculum/blob/master/ruby_programming/archive/basic_ruby/project_advanced_building_blocks.md#project-2-enumerable-methods)) ``
- After calling the given block once for each element in self, returns the array itself
```ruby
[1, 2, 3].my_each {|num| num}  #should return [1, 2, 3]
```

2020-05-25 19:16 UTC, shshamim63 commented on custom_enumerable_methods.rb
> +  end
`my_each_with_index` identical and returns the same thing as ruby's [`each_with_index`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-each_with_index). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_each_with_index.png) from [Odin](https://github.com/TheOdinProject/curriculum/blob/master/ruby_programming/archive/basic_ruby/project_advanced_building_blocks.md#project-2-enumerable-methods))
- After calling the given block once for each element in self, returns the array itself
```ruby
[1, 2, 3].my_each_with_index {|num| num}  #should return [1, 2, 3]
```

2020-05-25 19:16 UTC, shshamim63 commented on custom_enumerable_methods.rb
> +  end
`my_all?` identical and returns the same thing as ruby's [`all?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-all-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_all.png) from [Odin](https://github.com/TheOdinProject/curriculum/blob/master/ruby_programming/archive/basic_ruby/project_advanced_building_blocks.md#project-2-enumerable-methods)) 
- Just one more case, when no block or argument is given, returns true when none of the collection members are false or nil
```ruby
[1, 2, 3].my_all? #should return true
[1, 2, nil].my_all? #should return false
[1, false, nil].my_all? #should return false
```

2020-05-25 19:16 UTC, shshamim63 commented on custom_enumerable_methods.rb
> +  end
`my_map` identical and returns the same thing as ruby's [`map`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-map). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_map.png) from [Odin](https://github.com/TheOdinProject/curriculum/blob/master/ruby_programming/archive/basic_ruby/project_advanced_building_blocks.md#project-2-enumerable-methods))
![image](https://user-images.githubusercontent.com/38625956/82838260-72e0e300-9eed-11ea-9c3e-46a340a1d2fc.png)
- executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.
```ruby
my_proc = Proc.new { |num| num > 10 }
[11, 2, 3, 15].my_map(my_proc) {|num| num < 10 } # should return [true, false, false, true]
```

2020-05-26 12:22 UTC, Zubenna commented
Requested changes have been implemented. The specified methods have been modified. Required tests and parameters has been implemented in tests.rb file. They returned the expected result.

2020-05-26 13:00 UTC, stratospherique requested changes
### Great work implementing the suggested :clap: :clap: However, some methods need further refactoring in order to get approval for this project. Check :arrow_down: 

- **[REQUIRED]** Check the code comments below, they should help you refactor your methods :gear: 

### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-05-26 13:00 UTC, stratospherique commented on custom_enumerable_methods.rb
> +  end
* [ ] my_each returns an Enumerator if no block is given
  ```ruby
    array = [1,2,5,8,7,98,4]
    p array.my_each.class # not Enumerator
  ```

2020-05-26 13:00 UTC, stratospherique commented on custom_enumerable_methods.rb
> +  end
* [ ] my_all? identical and returns the same thing as ruby's all?. 

- Just one more case, when no block or argument is given, returns true when none of the collection members are false or nil
```ruby
[1, 2, 3].my_all? #should return true
[1, 2, nil].my_all? #should return false
[1, false, nil].my_all? #should return false
```

2020-05-26 13:00 UTC, stratospherique commented on custom_enumerable_methods.rb
> +  end
* [ ]  my_map executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.
   ```ruby
	my_proc = Proc.new { |num| num > 10 }
	[11, 2, 3, 15].my_map(my_proc) {|num| num < 10 } # should return [true, false, false, true]
   ```

2020-05-26 13:00 UTC, stratospherique commented on custom_enumerable_methods.rb
> +end
* [ ] my_inject combines all elements of enum by applying a binary operation, specified by a block
  ```ruby
    range = Range.new(5, 50)
    p range.my_inject(4) { |prod, n| prod * n } # returns this error
    # NameError:
       undefined local variable or method `length' for 5..50:Range
     # ./custom_enumerable_methods.rb:4:in `my_each'
     # ./custom_enumerable_methods.rb:225:in `my_inject'
  ```
* [ ] my_inject when a symbol is specified combines each element of the collection by applying the symbol as a named method
  ```ruby
    range = Range.new(5, 50)
    p range.my_inject(2, :*) # returns this error
    # NameError:
       undefined local variable or method `length' for 5..50:Range
     # ./custom_enumerable_methods.rb:4:in `my_each'
     # ./custom_enumerable_methods.rb:185:in `my_inject'
  ```

2020-05-26 16:38 UTC, Zubenna commented
I have modified the required methods as recommended.
Note that stickler does not accept definition of proc this way => my_proc = Proc.new { |num| num > 10 }
That was why I did not use it that way.

2020-05-26 18:47 UTC, mosesogwo requested changes
**Great job @Zubenna:clap:. Just a little more step and you can :rocket:**
- See this example, `[1, 2, false].my_all?`. It should return `false` as pointed out in the last review but currently it returns `true`. A similar example was given in the last review but with a `nil` element in the array. The logic is that if there is at least one element that is not a truthy (it could be a false or nil), then my_all? should return false when no block is given.

- Your *my_map* still doesn't handle the case where both a proc and a block are given correctly. Try incorporating this logic in your method:
```
  def my_map(my_proc = nil)
    new_array = []
    if !my_proc
      return to_enum unless block_given?
      my_each { |n| new_array << yield(n) }
    else
      my_each { |n| new_array << my_proc.call(n) }
    end
    new_array
  end
```


_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-05-26 22:41 UTC, Zubenna commented
Affected methods have been modified to implement recommendations.

2020-05-26 23:36 UTC, mosesogwo requested changes
**Hello:clap: It seems my_all? was broken while you were trying to implement the last review. Two test cases are now failing:**

:point_right: When a class is passed as argument, it should return true if all the elements are members of that class.
`[1, 2, 3, 4].my_al?l(Integer)` should return `true` 

:point_right: When a regex is passed as argument, it should return true if all the elements match that pattern.
`%w[dog, door, doll].my_all?(/d/)` should return `true`

Please address these cases and submit another code review request.

### Status: Changes Requested.

2020-05-27 02:10 UTC, Zubenna commented
Recommended changes has been implemented.

2020-05-27 10:44 UTC, mikenath223 requested changes
Hi @Zubenna  👋

You've come quite far on this.🚀

Let's fix the few remaining issues and you are good to go.👌
The issues basically exist with my_all.

- [ ] my_all, when a false block is passed to it, is expected to return false but yet returned true. Kindly fix this.

- [ ] my_all, also when no block or argument is given should return true if the array passed to it has no false member but yours returns false.

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-05-27 15:22 UTC, Zubenna commented
I have implemented requested change.

2020-05-27 17:26 UTC, shshamim63 commented
## Status :100: Approved
___
Hi @Zubenna :wave:
Awesome job. You have successfully covered all the changes. and all your methods are working as they should. Nothing is blocking me to approve it. This :+1: is from me.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-05-27 17:51 UTC, merged